### create a meme
POST http://localhost:3000/memes
Content-Type: application/json

{
  "key": "분노",
  "personName": "박명수",
  "path": "images/2.jpg",
  "subtitle": "꼴 보기 싫어"
}

### get all memes
GET http://localhost:3000/memes

### get a meme
GET http://localhost:3000/memes/1

### get a filtered memes
GET http://localhost:3000/memes/search?key=행복&&personName=박명수
