POST http://localhost:3000/memes
Content-Type: application/json

{
  "key": "행복",
  "personName": "박명수",
  "path": "/images/1.jpg",
  "subtitle": "나는 행복한 놈이다..."
}

### get one
GET http://localhost:3000/memes/815

### get all
GET http://localhost:3000/memes
Content-Type: application/json

### search
GET http://localhost:3000/memes/search?key=행복&&personName=박명수

